name = "Fixed Amount"
type = "product_discounts"
api_version = "2023-01"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/fixed-amount.wasm"

[ui.paths]
create = "/"
details = "/"
