[package]
name = "shipping-discount"
version = "1.0.0"
edition = "2021"
include = ["*.graphql"]

[dependencies]
serde = { version = "1.0.13", features = ["derive"] }
serde_with = "1.13.0"
serde_json = "1.0"

[profile.release]
lto = true
opt-level = 'z'
strip = true
