name = "Shipping Discount"
type = "shipping_discounts"
api_version = "unstable"

[ui.paths]
create = "/shipping-discount/new"
details = "/shipping-discount/:id"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/shipping-discount.wasm"
