[package]
name = "default"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
serde = { version = "1.0.13", features = ["derive"] }

[profile.release]
lto = true
opt-level = 's'
