name = "Order Discount"
type = "order_discounts"
api_version = "unstable"

[ui.paths]
create = "/order-discount/new"
details = "/order-discount/:id"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/order-discount.wasm"
