name = "Volume"
type = "product_discounts"
api_version = "2022-07"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/volume.wasm"

[ui.paths]
create = "/volume/new"
details = "/volume/:id"
